spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schemas: public
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${AWS_CLIENT_ID}
            client-secret: ${AWS_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          cognito:
            authorization-uri: https://${AWS_NAME}.auth.${AWS_REGION}.amazoncognito.com/oauth2/authorize
            token-uri: https://${AWS_NAME}.auth.${AWS_REGION}.amazoncognito.com/oauth2/token
            user-info-uri: https://${AWS_NAME}.auth.${AWS_REGION}.amazoncognito.com/oauth2/userInfo
            user-name-attribute: sub
    resourceserver:
      jwt:
        issuer-uri: https://${AWS_NAME}.auth.${AWS_REGION}.amazoncognito.com

aws:
  cognito:
    pool-id: ${AWS_USER_POOL_ID}
    client-id: ${AWS_CLIENT_ID}
    region: ${AWS_REGION}

logging:
  level:
    com.totalfitx.backend: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE

springdoc:
  api-version: 0.0.1
  swagger-ui:
    oauth:
      auth-uri: "http://dummy.auth-uri"
